default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trpo_dev
  username: postgres
  password: root-pas
  host: localhost

test:
  <<: *default
  database: trpo_test

production:
  <<: *default
  database: trpo_production
  username: wlapp_db_admin
  password: wlapp-db-pas
  host: localhost
